// Mocks generated by Mockito 5.4.4 from annotations
// in clarity_frontend/test/features/courses/presentation/course_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:clarity_frontend/core/data/interfaces/i_course_repository.dart'
    as _i2;
import 'package:clarity_frontend/features/courses/bloc/course_bloc.dart' as _i4;
import 'package:clarity_frontend/features/courses/bloc/course_event.dart'
    as _i6;
import 'package:clarity_frontend/features/courses/bloc/course_state.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeICourseRepository_0<TCourse> extends _i1.SmartFake
    implements _i2.ICourseRepository<TCourse> {
  _FakeICourseRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourseState_1 extends _i1.SmartFake implements _i3.CourseState {
  _FakeCourseState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CourseBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseBloc extends _i1.Mock implements _i4.CourseBloc {
  @override
  _i2.ICourseRepository<dynamic> get courseRepository => (super.noSuchMethod(
        Invocation.getter(#courseRepository),
        returnValue: _FakeICourseRepository_0<dynamic>(
          this,
          Invocation.getter(#courseRepository),
        ),
        returnValueForMissingStub: _FakeICourseRepository_0<dynamic>(
          this,
          Invocation.getter(#courseRepository),
        ),
      ) as _i2.ICourseRepository<dynamic>);

  @override
  _i3.CourseState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeCourseState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeCourseState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.CourseState);

  @override
  _i5.Stream<_i3.CourseState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.CourseState>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.CourseState>.empty(),
      ) as _i5.Stream<_i3.CourseState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i6.CourseEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.CourseEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.CourseState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.CourseEvent>(
    _i7.EventHandler<E, _i3.CourseState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i7.Transition<_i6.CourseEvent, _i3.CourseState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i3.CourseState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
