services:
  # Runner
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - nginx:/app/dev/usr/share/nginx/html:rw

  # Runner Register
  gitlab-runner-register:
    image: gitlab/gitlab-runner:latest
    restart: "no"
    container_name: gitlab-runner-register
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_EXECUTOR=docker
    command: 
      - register 
      - --non-interactive
      - --locked=false
      - --url=${CI_SERVER_URL}
      - --registration-token=${REGISTRATION_TOKEN}
      - --executor=docker
      - --docker-image="cirruslabs/flutter:stable"
      - --description="gitlab-runner"
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
      - --docker-volumes=nginx:/app/dev/usr/share/nginx/html

    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
    
  # DEV Frontend
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5000:80"
    volumes:
      - nginx:/usr/share/nginx/html:ro
    environment:
      - ENV=DEV

volumes:
  nginx:
    name: nginx