name: clarity_frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  husky: ^0.1.7
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true