name: clarity_frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttericon: ^2.0.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  husky: ^0.1.7
  numerus: ^2.2.0
  provider: ^6.1.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
