concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "\"gitlab-runner\""
  url = "https://tools.ages.pucrs.br/"
  id = 483
  token = "zCh_2RB6ztardKxWEQdA"
  token_obtained_at = 2024-09-01T22:12:49Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "\"cirruslabs/flutter:stable\""
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "nginx:/app/dev/usr/share/nginx/html", "/cache"]
    shm_size = 0
    network_mtu = 0
